### ISSUE TITLE
Cho phép cấu hình thông tin thới khóa biểu trong admin

### ISSUE THREAD

**Issue by quangcuong** [quocdatit/nv-tkb#1]
Hiện tại mình thấy muốn cấu hình thông tin thì phải sửa code chứ trong admin không cho cấu hình. Vì vậy đề xuất cho phép cấu hình thông tin trong admin luôn cho tiện
"THỜI KHÓA BIỂU....Áp dụng từ ngày..."

**Comment by quocdatit** [comment]
Đã update! https://github.com/quocdatit/nv-tkb/commit/2c7c3c33300e61af1f989417322109f748f5a148
Xóa module hiện tại, tải bản mới về, Giải nén đè lên module cũ, Thiết lập lại module: là ok ạ!
