### ISSUE TITLE
Thêm hàng cho bảng dữ liệu

### ISSUE THREAD

**Issue by quangcuong** [quocdatit/nv-tkb#2]
Chào tác giả!
Modules rất hay, nhưng hiện tại tkb lớp mỗi ngày hỉ có 5 hàng (5 tiết). Tác giả có thể thêm hàng cho file mẫu được không?

**Comment by quocdatit** [comment]
@quangcuong thêm bao nhiêu hàng vậy anh

**Comment by quocdatit** [comment]
@quangcuong em đã cập nhật version 1.0.01 lên kho module của nukeviet rồi nha anh.
https://nukeviet.vn/vi/store/modules/tkb/
